#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
export PATH="$HOME/doc/software/bin:$HOME/doc/software/pkg/cargo/bin:$HOME/.local/bin:$HOME/.config/npm/bin:$PATH"
export LANG=en_US.UTF-8
export LC_ALL=$LANG
export EDITOR="ecli"
export TEXMFHOME=~/.config/texmf
export RUSTUP_HOME="$HOME/doc/software/pkg/rustup"
export CARGO_HOME="$HOME/doc/software/pkg/cargo"
_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djava.net.useSystemProxies=true'
