#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source /etc/profile.d/vte.sh
bindkey "$key_info[Escape]f" forward-word
bindkey "$key_info[Escape]\r" autosuggest-execute
setopt rmstarsilent
export TERM=xterm-256color
unset GREP_COLORS
